services:
  - docker
notifications:
  email: false
language: node_js
node_js: '10'
os: linux
before_install:
  - docker pull doscode/gruut-nodejs:latest
  - docker run --name gruut-tracker -d doscode/gruut-nodejs:latest
script:
  - docker exec gruut-tracker sh -c "
    service redis-server start
    "
  - docker exec gruut-tracker sh -c "
    mkdir -p workspace;
    cd workspace;
    git clone --branch=master https://github.com/gruut/gruut-tracker.git;
    cd gruut-tracker;
    rm -f package-lock.json;
    npm install;
    npm run lint;
    npm run test
    "
